/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT1_8 (coord A1), PIO1_8
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ULTRASONIC_TRIG_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ULTRASONIC_TRIG_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ULTRASONIC_TRIG_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT1_9 (coord B1), PIO1_9
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ULTRASONIC_ECHO_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ULTRASONIC_ECHO_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ULTRASONIC_ECHO_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT0_20 (coord C8), P0_20/J8[8]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_SW2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_SW2_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_SW2_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_SW2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_SW2_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_SW2_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORT0_1 (coord A16), P0_1/SWCLK/JP8[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT0_0 (coord A17), P0_0/SWDIO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                         /* @} */

/*! @name PORT0_2 (coord B16), P0_2/SWO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void);

/*! @name PORT4_17 (coord R9), P4_17/J4[8]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_BLUE_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_18 (coord N10), P4_18/J5[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_RED_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RED_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT4_19 (coord R10), P4_19/J8[11]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT0_20 (coord C8), P0_20/J8[8]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW2_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT0_6 (coord C14), P0_6/J12[7]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT2_0 (coord H2), P2_0/SJ3[1]/J1[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_TRIG_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_TRIG_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_TRIG_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_TRIG_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_TRIG_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_TRIG_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_TRIG_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT2_1 (coord H1), P2_1/J9[30]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_ECHO_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_ECHO_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_ECHO_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_ECHO_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_ECHO_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITULTRASONICPINS_ULTRASONIC_ECHO_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitULTRASONICPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT2_2 (coord H3), P2_2/J9[16]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITIRPINS_IR_OUT_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITIRPINS_IR_OUT_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITIRPINS_IR_OUT_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITIRPINS_IR_OUT_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITIRPINS_IR_OUT_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITIRPINS_IR_OUT_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitIRPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT2_3 (coord J3), P2_3/J8[20]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDHTPINS_DHT_DATA_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDHTPINS_DHT_DATA_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITDHTPINS_DHT_DATA_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDHTPINS_DHT_DATA_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDHTPINS_DHT_DATA_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITDHTPINS_DHT_DATA_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDHTPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
